services:
  - type: web
    name: whale-platform-backend
    env: docker
    plan: free
    region: oregon
    dockerContext: ./backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${DB_HOST}:${DB_PORT}/whaledb
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: whale-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: whale-db
          property: password

  - type: web
    name: whale-platform-frontend
    env: docker
    plan: free
    region: oregon
    dockerContext: ./frontend
    dockerfilePath: ./Dockerfile

databases:
  - name: whale-db
    plan: free
    databaseName: whaledb
    user: postgres
    region: oregon
